# This file should not be used in deployed environments. Instead, set
# the SETTINGS_PATH environment variable to point to a configuration
# file that contains these settings.

defaults: &defaults
  log_path: 'log/<%= Rails.env %>.log'
  auth_username: cc_admin

  services:
  - id: cf-amazons3
    name: cf-amazons3
    description: Cloud Foundry Amazons3 Service
    tags: ['Amazons3', 'storage']
    max_buckets_per_node: 200
    metadata:
      provider:
        name:    
      listing:
        imageUrl: ~
        blurb: Amazons3 Service for testing and development
    plans:
    - id: cf-amazons3-plan-1
      name: free2
      description: Free Trial
      max_storage_mb: 100 # in MB
      metadata:
        cost: 0.0
        bullets:
        - content: Shared new bucket
        - content: 100 MB storage

production:
  auth_password: 'secret'
  <<: *defaults

development:
  auth_password: 'secret'
  <<: *defaults

test:
  auth_password: 'secret'
  <<: *defaults